/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:63506684-02dd-4a71-88b8-7a8cce6c9541",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Ho1vGKEE2",
    "aws_user_pools_web_client_id": "16lht3uoldfjlhdj70qh7b3246",
    "oauth": {}
};


export default awsmobile;
